services:
  - type: web
    name: pdf-signer-backend
    env: node
    region: singapore
    plan: free
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: MONGODB_URI
        value: mongodb+srv://aayushsharma4518_db_user:BVSckEXJUPLORpwj@cluster0.crlzopw.mongodb.net/pdf_signer?appName=Cluster0
      - key: JWT_SECRET
        value: myPDFsignerSecret2024!@#
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: CLIENT_URL
        value: https://pdf-sign-azure.vercel.app
      - key: EMAIL_HOST
        value: smtp.gmail.com
      - key: EMAIL_PORT
        value: 587
      - key: EMAIL_USER
        value: aayushsharmahrx@gmail.com
      - key: EMAIL_PASS
        sync: false
